import oracledb
import os

wallet_dir = os.path.abspath("oracle_wallet")

connection = oracledb.connect(
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    dsn=os.getenv("DB_DSN"),
    wallet_password=os.getenv("WALLET_PASSWORD"),
    wallet_location=wallet_dir,
    config_dir=wallet_dir
)

cursor = connection.cursor()

# Check DB connectivity first
cursor.execute("SELECT SYSDATE FROM dual")
print(f"✅ Database connected! SYSDATE: {cursor.fetchone()[0]}")

# Drop the test table if it exists
try:
    cursor.execute("DROP TABLE test_table PURGE")
    print("🗑️ Dropped existing table 'test_table'.")
except oracledb.Error as e:
    if "ORA-00942" in str(e):
        print("⚠️ Table 'test_table' did not exist, skipping drop.")
    else:
        raise

# Create new test_table
cursor.execute("""
CREATE TABLE test_table (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR2(100),
    created_date DATE DEFAULT SYSDATE,
    PRIMARY KEY (id)
)""")
print("✅ Created new table 'test_table'.")

# Verify table creation (optional check)
cursor.execute("SELECT COUNT(*) FROM test_table")
count = cursor.fetchone()[0]
assert count == 0, "New table should be empty initially"
print("✅ Verified new table is empty.")

# Clean up
cursor.close()
connection.commit()  # Commit the changes explicitly
connection.close()
