name: Oracle Autonomous DB Workflow

on:
  push:
    branches:
      - main

jobs:
  oracle-db-test:
    runs-on: ubuntu-latest

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DSN: ${{ secrets.DB_DSN }}
      WALLET_PASSWORD: ${{ secrets.WALLET_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install oracledb
        run: |
          pip install oracledb

      - name: Decode & Extract Wallet
        run: |
          echo "${{ secrets.WALLET_ZIP }}" | base64 --decode > wallet.zip
          unzip wallet.zip -d oracle_wallet

      - name: Test Oracle DB Connection
        run: |
          python - <<'EOF'
          import oracledb
          import os

          wallet_dir = os.path.abspath("oracle_wallet")

          connection = oracledb.connect(
              user=os.getenv("DB_USER"),
              password=os.getenv("DB_PASSWORD"),
              dsn=os.getenv("DB_DSN"),
              wallet_password=os.getenv("WALLET_PASSWORD"),
              wallet_location=wallet_dir,
              config_dir=wallet_dir
          )

          cursor = connection.cursor()
          cursor.execute("SELECT SYSDATE FROM dual")
          result = cursor.fetchone()
          print(f"✅ Connected successfully! SYSDATE: {result[0]}")

          cursor.close()
          connection.close()
          EOF
