name: Oracle Autonomous DB (with wallet)

on:
  push:
    branches:
      - main

jobs:
  oracle-db-test:
    runs-on: ubuntu-latest

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DSN: ${{ secrets.DB_DSN }}
      WALLET_PASSWORD: ${{ secrets.WALLET_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Oracle DB driver
        run: pip install oracledb

      - name: Decode & Extract Wallet
        run: |
          echo "${{ secrets.WALLET_ZIP }}" | base64 --decode > wallet.zip
          unzip wallet.zip -d oracle_wallet

      - name: Test Oracle DB Connection
        run: |
          python - <<EOF
          import oracledb
          import os

          wallet_dir = os.path.abspath("oracle_wallet")
          os.environ["TNS_ADMIN"] = wallet_dir

          conn = oracledb.connect(
              user="${{ secrets.DB_USER }}",
              password="${{ secrets.DB_PASSWORD }}",
              dsn="${{ secrets.DB_DSN }}",
              wallet_password="${{ secrets.WALLET_PASSWORD }}",
              config_dir=wallet_dir,
              wallet_location=wallet_dir,
              ssl_server_dn_match=True
          )

          with conn.cursor() as cursor:
              cursor.execute("SELECT SYSDATE FROM dual")
              result = cursor.fetchone()
              print(f"✅ Connected successfully! SYSDATE: {result[0]}")

          conn.close()
          EOF

      - name: Decode and Extract Wallet (with password)
        run: |
          echo "${{ secrets.WALLET_ZIP }}" | base64 --decode > wallet.zip
          unzip wallet.zip -d oracle_wallet
