name: Oracle DB Connection Workflow

on:
  push:
    branches:
      - main

jobs:
  oracle-test:
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DSN: ${{ secrets.DB_DSN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install python-oracledb
        run: |
          pip install oracledb

      - name: Verify Oracle DB connectivity
        run: |
          python - << 'PYCODE'
          import oracledb
          import os

          user = os.environ["DB_USER"]
          password = os.environ["DB_PASSWORD"]
          dsn = os.environ["DB_DSN"]

          try:
              connection = oracledb.connect(user=user, password=password, dsn=dsn)
              cursor = connection.cursor()
              cursor.execute("SELECT SYSDATE FROM dual")
              result = cursor.fetchone()
              print(f"Database connected, SYSDATE is {result[0]}")
          except oracledb.Error as e:
              print(f"Error connecting to the database: {e}")
          finally:
              if cursor:
                  cursor.close()
              if connection:
                  connection.close()
          PYCODE
